theme: jekyll-theme-tactile
title: Welcome to Kenny Waite's Data Science Portfolio 
description: This page gives and overview of the various data science projects I have worked on throughout my career. Please explore the different projects to gain additional insights into my data scientist skill set.
