remote_theme: jekyll-theme-tactile
title: Kenny Waite
description: Data Scientist solving complex problems leveraging business domain knowledge and analytics
#description: This page gives and overview of the various data science projects I have worked on throughout my career. Please explore the different projects to gain additional insights into my data scientist skill set.
