---
title: "DSC 640 Assignment 3.2"
author: "Kenny Waite"
date: "10/6/2020"
output: html_document
---

```{r setup, include=FALSE, collapse=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(plotly)
library(dplyr)
library(ggplot2)
library(treemap)
data <- read.csv("expenditures.txt", sep="\t")
data
```
<br>

```{r echo=FALSE, message=FALSE, comment = NA, warning=FALSE, collapse=TRUE, tidy=TRUE}
# area chart
addUnits <- function(n) {
  labels <- ifelse(n < 1000, n,  # less than thousands
                   ifelse(n < 1e6, paste0(round(n/1e3), 'k'),  # in thousands
                          ifelse(n < 1e9, paste0(round(n/1e6), 'M'),  # in millions
                                 ifelse(n < 1e12, paste0(round(n/1e9), 'B'), # in billions
                                        ifelse(n < 1e15, paste0(round(n/1e12), 'T'), # in trillions
                                               'too big!'
                                        )))))
  return(labels)
}
# groupby dataframe
by_year <- aggregate(data$expenditure, by=list(Category=data$year), FUN=sum)
# Plot
ggplot(by_year, aes(x=Category, y=x)) +labs(title='Expenses by Year', x ="Year", y = "Expenses") + geom_area( fill="#69b3a2", alpha=0.4) + scale_y_continuous(labels = addUnits)
```

<br>

```{r echo=FALSE, message=FALSE, comment = NA, warning=FALSE, collapse=TRUE, tidy=TRUE}
# stacked area chart
# create data
top_five <- filter(data, data$category=='Housing' | data$category=='Transportation' | data$category=='Food' |
                   data$category=='Personal Insurance' | data$category=='Healthcare')
ggplot(top_five, aes(x=year, y=expenditure, fill=category)) + 
    geom_area(alpha=0.6) + scale_fill_manual(values = c("blue","gold","green","orange","tan")) + scale_y_continuous(labels = addUnits) +labs(title='Top 5 Expenses by Year', x ="Year", y = "Expenses")
```

<br>

```{r echo=FALSE, message=FALSE, comment = NA, warning=FALSE, collapse=TRUE, tidy=TRUE}
# tree chart
treemap(data, index=c('category'), vSize='expenditure', type="index", title="Total Expensises Since 1985")
